# This Kubernetes Role will be bound to the group configured in our Teleport Role.
# It grants the privileges needed to deploy, and nothing more.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: colormatic
  name: colormatic-deployer
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
