apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: colormatic
  name: colormatic
  namespace: colormatic
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: colormatic
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: colormatic
    spec:
      containers:
        # This image tag is replaced with a real image tag during CI
        - image: ghcr.io/strideynet/machineid-github-kubernetes-webinar/colormatic:latest
          name: colormatic
          ports:
            - containerPort: 9090
              protocol: TCP
          resources: {}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Always